config/routes.rb
Rails.application.routes.draw do
  resources :articles, only: [:create, :update]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  namespace :admin do
    resources :articles do
      member do
        get :approve
        post :approve_update
        get :approve_with_comments
        post :approve_with_comments_update
        get :reject
        get :modal_cancel
      end
    end
  end
  get 'report' => 'articles#report', as: :report_article
  get 'translation' => 'articles#translation', as: :translation_article
  get 'articles/:article_token/edit' => 'articles#edit', as: :edit_article
  get 'articles/:article_token/submit_comments' => 'articles#submit_comments', as: :submit_comments_article
  get 'articles/note' => 'articles#note', as: :note_article

  root 'articles#report'

end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :line_manager
	belongs_to :editor
	belongs_to :user
	belongs_to :assignment
  belongs_to :publisher
  belongs_to :designer
  belongs_to :interest
  belongs_to :status
  belongs_to :article_country
  belongs_to :incident_country, class_name: "Country"
  belongs_to :article_type
  belongs_to :team
  has_many :message_logs
  has_and_belongs_to_many :personas
  validates :user_id, presence: true

  enum approval_status: {approved: 3, inquired: 2, rejected: 1, pending: 0}
  MATERIALS_LIST = ["فيديو", "صور", "فيديو وصور"]
  EXECUTION_METHOD_LIST = ["مادة قائمة على التعددات", "فيتشر ستوري", "تقرير خبري", "آخر"]
  ALLOWED_ATTRIBUTES = [
                :title,
              :original_link,
              :interest_id,
              :article_type_id]
  attr_accessor :skip_save_to_sheet
  
  scope :created_between, lambda {|s, e| where(created_at: s.to_date.beginning_of_day..e.to_date.end_of_day)}
  scope :created_daily, -> {where(created_at: Date.today.beginning_of_day..Date.today.end_of_day)}
  scope :created_weekly, -> {where(created_at: Date.today.at_beginning_of_week(start_day= :sunday)..Date.today.at_end_of_week(start_day= :sunday))}
  scope :created_monthly, -> {where(created_at: Date.today.beginning_of_month..Date.today.end_of_month)}
  scope :created_daily_by_interest, lambda {|i| where(interest_id: i, created_at: Date.today.beginning_of_day..Date.today.end_of_day)}
  scope :created_weekly_by_interest, lambda {|i| where(interest_id: i, created_at: Date.today.at_beginning_of_week(start_day= :sunday)..Date.today.at_end_of_week(start_day= :sunday))}
  scope :created_monthly_by_interest, lambda {|i| where(interest_id: i, created_at: Date.today.beginning_of_month..Date.today.end_of_month)}
  scope :created_daily_by_article_country, lambda {|ac| where(article_country_id: ac, created_at: Date.today.beginning_of_day..Date.today.end_of_day)}
  scope :created_weekly_by_article_country, lambda {|ac| where(article_country_id: ac, created_at: Date.today.at_beginning_of_week(start_day= :sunday)..Date.today.at_end_of_week(start_day= :sunday))}
  scope :created_monthly_by_article_country, lambda {|ac| where(article_country_id: ac, created_at: Date.today.beginning_of_month..Date.today.end_of_month)}
  scope :translation, -> {where(team_id: Team.where(name: "مراسلون").first.try(:id))}
  scope :report, -> {where(team_id: Team.where(name: "ترجمة").first.try(:id))}
  scope :approved, -> {where("approval_status = 3")}
  scope :inquired, -> {where("approval_status = 2")}
  scope :rejected, -> {where("approval_status = 1")}
  scope :pending, -> {where("approval_status = 0")}
  scope :all_states, -> {where("approval_status in (0, 1, 2, 3)")}

  before_create :generate_token
  before_save :notify_on_status_change
  before_save :calculate_progress_bar
  before_save :calculate_sections_progress_bar
  after_save :save_to_sheet, unless: Proc.new { |article| article.skip_save_to_sheet }

  def reporter_id
    self.user_id
  end
  
  def reporter
    self.user
  end

  def calculate_progress_bar
    if self.start_date.present? && self.deadline.present?
      total_period = (self.deadline.to_date - self.start_date.to_date).to_i
      passed_period = (Date.today - self.start_date.to_date).to_i
      self.progress_bar = (passed_period.to_f / total_period) * 100
    end
  end

  def calculate_sections_progress_bar
    if self.interest.present?
      daily_percentage = (Article.created_daily_by_interest(self.interest_id).count.to_f / self.interest.daily_target) * 100
      weekly_percentage = (Article.created_weekly_by_interest(self.interest_id).count.to_f / self.interest.weekly_target) * 100
      monthly_percentage = (Article.created_monthly_by_interest(self.interest_id).count.to_f / self.interest.monthly_target) * 100
      self.sections_progress_bar = "Daily: #{daily_percentage.round(0)}%, Weekly: #{weekly_percentage.round(0)}%, Monthly: #{monthly_percentage.round(0)}%" 
    end
  end

  def save_to_sheet
    unless ["rejected"].include? self.approval_status
      session = GoogleDrive::Session.from_config("client_secret.json")
      ws = session.spreadsheet_by_key(SPREADSHEET_KEY).worksheets[0]

      row_id = self.sheet_row || (ws.num_rows + 1)
      self.update_column(:sheet_row, row_id) if self.sheet_row.blank?
      # T.Stump 
      # L.M. eMail  
      # Status  
      # Title 
      # Start Date  
      # Deadline  
      # Delivery Time 
      # Progress Bar  
      # Editor  
      # eMail 
      # eMai Sent 
      # Reporters 
      # From  
      # Assignment  
      # Drive 
      # Country 
      # Interest 
      # Sections Progress Bar 
      # CMS Link  
      # Notes           


      # T.Stamp Line Manager  Status  Title Start Date  Deadline  Publish Date  Publish Time  
      # Progress Bar  Editor  eMail eMai Sent Reporters From  Assignment  Drive Country 
      # Interests Sections Progress Bar CMS Link  Notes
      ws[sheet_row, 1] = self.id
      ws[sheet_row, 2] = self.created_at
      ws[sheet_row, 3] = self.article_type.try(:name)
      ws[sheet_row, 4] = self.team.try(:name)
      ws[sheet_row, 5] = self.title
      ws[sheet_row, 6] = self.details
      ws[sheet_row, 7] = self.personas.pluck(:name).join(", ")
      ws[sheet_row, 8] = self.article_country.try(:name)
      ws[sheet_row, 9] = self.processing_point_of_view
      ws[sheet_row, 10] = self.resources
      ws[sheet_row, 11] = self.resources_links
      ws[sheet_row, 12] = self.materials
      ws[sheet_row, 13] = self.why_publish
      ws[sheet_row, 14] = self.interest.try(:title)
      ws[sheet_row, 15] = self.editor.try(:email)
      ws[sheet_row, 16] = self.user.try(:email)
      ws[sheet_row, 17] = self.assignment.try(:name)
      ws[sheet_row, 18] = self.line_manager.try(:email)
      ws[sheet_row, 19] = self.publisher.try(:email)
      ws[sheet_row, 20] = self.deadline ? I18n.l(self.deadline.to_date, format: :default) : ""
      ws[sheet_row, 21] = self.deadline ? I18n.l(self.deadline, format: :time_only) : ""
      ws[sheet_row, 22] = self.publish_date ? I18n.l(self.publish_date.to_date, format: :default) : ""
      ws[sheet_row, 23] = self.publish_date ? I18n.l(self.publish_date, format: :time_only) : ""
      ws[sheet_row, 24] = self.drive_link
      ws[sheet_row, 25] = self.cms_link
      ws[sheet_row, 26] = self.original_words_count
      ws[sheet_row, 27] = self.reporter_desk_notes
      ws[sheet_row, 28] = self.trans_desk_notes
      ws[sheet_row, 29] = self.reporter_notes
      ws[sheet_row, 30] = self.manager_notes
      ws[sheet_row, 31] = self.article_token
      ws[sheet_row, 32] = self.publish_flag
      ws[sheet_row, 33] = self.status.try(:name)
      ws[sheet_row, 34] = self.designer.try(:email)
      ws[sheet_row, 35] = self.progress_bar ? "#{self.progress_bar} %" : "0%"
      ws[sheet_row, 36] = self.sections_progress_bar
      messages = []
      self.message_logs.each do |m|
        messages << "At #{m.created_at} #{m.description}"
      end
      ws[sheet_row, 37] = messages.join(", ")
      ws.save
    end
  end

  def notify_on_status_change
    if self.status_id.present? && self.status_id_changed? && self.status.key == "published"
      UserMailer.article_published(self.line_manager_id, self.id).deliver_now
      MessageLog.create(log_type: "article_published", description: "Line manager #{self.line_manager.name} is notified by article publishing", article_id: self.id)
      UserMailer.article_published_to_reporter(self.user_id, self.id).deliver_now
      MessageLog.create(log_type: "article_published", description: "Reporter #{self.user.name} is notified by article publishing", article_id: self.id)
    end
  end

  def notify_line_manager_when_publish_date_overdue
    if self.line_manager_id.present?
      UserMailer.article_overdue(self.line_manager_id, self.id).deliver_now
      MessageLog.create(log_type: "article_overdue", description: "Line manager #{self.line_manager.name} is notified by article's publish date overdue", article_id: self.id)
    end
  end

  def notify_line_manager_when_publish_date_near(period)
    if self.editor_id.present?
      UserMailer.article_near(self.editor_id, self.id, period).deliver_now
      MessageLog.create(log_type: "article_near_#{period}", description: "Editor #{self.editor.name} is notified by article deadline #{period} away", article_id: self.id)
    end
  end

  def notify_on_approval
    UserMailer.article_approved(self.line_manager_id, self.id).deliver_now if self.line_manager_id.present?
    MessageLog.create(log_type: "article_approved", description: "Line manager #{self.line_manager.name} is notified by article approval", article_id: self.id) if self.line_manager_id.present?
    UserMailer.article_approved(self.editor_id, self.id).deliver_now if self.editor_id.present?
    MessageLog.create(log_type: "article_approved", description: "Editor #{self.editor.name} is notified by article approval", article_id: self.id) if self.editor_id.present?
    UserMailer.article_approved_to_reporter(self.user_id, self.id).deliver_now
    MessageLog.create(log_type: "article_approved", description: "Reporter #{self.user.name} is notified by article approval", article_id: self.id)
  end

  def notify_reporter_on_comments_reply
    if self.line_manager_id.present?
      UserMailer.article_notify_with_reply_comments(self.line_manager_id, self.id).deliver_now 
      MessageLog.create(log_type: "reporter_reply_on_inquiry", description: "Line manager #{self.line_manager.name} is notified by reporter's reply on inquiry", article_id: self.id)
    end
    if self.editor_id.present?
      UserMailer.article_notify_with_reply_comments(self.editor_id, self.id).deliver_now 
      MessageLog.create(log_type: "reporter_reply_on_inquiry", description: "Editor #{self.editor.name} is notified by reporter's reply on inquiry", article_id: self.id)
    end
  end

  def notify_on_approval_with_comments
    if self.editor_id

app/models/article_type.rb
class ArticleType < ActiveRecord::Base
	has_many :articles
  before_save :update_key

  def update_key
    self.key = "ArticleType#{ArticleType.all.count + 1}" if self.key.blank?
    self.key = self.key.strip.gsub(" ", "").camelcase
  end
end

app/controllers/articles_controller.rb
class ArticlesController < InheritedResources::Base
  before_filter :load_reporter_by_email, only: [:create]
  before_filter :load_article, only: [:edit, :submit_comments]
  before_filter :set_locale

  def report
    @article = Article.new(team: Team.where(name: "مراسلون").first)
  end

  def translation
    @article = Article.new(team: Team.where(name: "ترجمة").first)
  end

  def create
    @article = Article.new(article_params)
    if @user.present? && @article.save
      @article.notify_reporter_on_submission
      redirect_to note_article_path(token: @article.article_token)
    else
      if @user.present? && !@article.valid?
        params[:article][:user_id] = @user.email
        render action: (@article.team.try(:name) == "مراسلون" ? "report" : "translation")
      elsif params[:article][:user_id].present? && !@article.valid?
        render action: (@article.team.try(:name) == "مراسلون" ? "report" : "translation")
      elsif !params[:article][:user_id].present? && !@article.valid?
        render action: (@article.team.try(:name) == "مراسلون" ? "report" : "translation")
      else
        UserMailer.anonymous_article_submitted(params[:article][:user_id], @article.title).deliver_now
        options = @article.attributes.reject{|k,v| !(Article::ALLOWED_ATTRIBUTES.include?(k.to_sym))}
        UserMailer.anonymous_article_submision_notification(ANONY_MAILER_RECEIVER, params[:article][:user_id], options).deliver_now
        redirect_to note_article_path(title: @article.title)
      end
    end
  end

  def update
    @article = Article.find params[:id]
    if params[:article][:approval_comments_reply].present?
      if @article.update_attributes(article_params)
        @article.notify_reporter_on_comments_reply
        redirect_to note_article_path(token: @article.article_token)
      else
        render action: 'submit_comments'
      end
    else
      @article.status = Status.where(key: "received").first
      if @article.update_attributes(article_params)
        @article.notify_on_updates
        redirect_to note_article_path(token: @article.article_token)
      else
        render action: 'edit'
      end
    end
  end

  def note
    @article = Article.where(article_token: params[:token]).first
    @article_title = params[:title]
  end

  private
    def load_reporter_by_email
      @user = User.where(type: "Reporter", email: params[:article][:user_id]).first
      params[:article][:user_id] = @user.id if @user.present?
    end

    def load_article
      @article = Article.where(article_token: params[:article_token]).first
    end

    def article_params
      params.require(:article).permit(:team_id, :user_id, :interest_id, :article_type_id,
        :title, :original_link,
        :suggested_idea, :incident_date, :incident_country_id, :processing_point_of_view,
        :why_publish, :resources, :resources_links, :execution_method, :materials, :deadline,
        :drive_link, :final_title, :translated_words_count, :original_words_count, :approval_comments_reply)
    end

    def set_locale
      I18n.locale = :ar
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/admin/articles/_edit_static_part.html.erb
<!-- <li class="string input optional stringish" id="article_title_input">
  <label for="article_title" class="label">Title</label>
  <span id="article_title" name="article[title]"><%#= object.title %></span>
</li> -->
<li class="select input optional" id="article_user_input">
  <label for="article_user_id" class="label">User</label>
  <span name="article[user_id]" id="article_user_id"><%= link_to object.user.name, admin_user_path(object.user) %></span>
</li>

app/views/admin/articles/approve.html.erb
<div class="fancybox_outlayer">
<div class="title_bar" id="title_bar">
  <div id="titlebar_left">
    <h2 id="page_title">Approve Article</h2>
  </div> 
</div>
<div class="flashes"></div>
<div id="active_admin_content" class="without_sidebar">
  <div id="main_content_wrapper">
    <div id="main_content">

      <%= form_for(@article, url: approve_update_admin_article_path, method: :post, remote: true, html: {class: "formtastic"}) do |f| %>
        <fieldset class="inputs"><!-- inputs -->
          <ol>
            <li class="" id="article_line_manager_id_input">
              <%= f.label :line_manager %>
              <%= f.select(:line_manager_id, LineManager.all.collect {|s| [s.name, s.id ] }, { include_blank: true }, class: "form-control") %>
            </li>
            <li class="" id="article_editor_id_input">
              <%= f.label :editor %>
              <%= f.select(:editor_id, Editor.all.collect {|s| [s.name, s.id ] }, { include_blank: true }, class: "form-control") %>
            </li>
          </ol>
        </fieldset>

        <fieldset class="actions">
          <ol>
            <li class="cancel">
              <%= link_to "Cancel", modal_cancel_admin_article_path(@article), remote: true %>
            </li>
            <li id="article_submit_action" class="action input_action ">
              <input type="submit" value="Approve" name="commit">
            </li>
            <!-- <li class="cancel">
              <a href="/admin/mailboxer_conversations">إلغاء</a>
            </li> -->
          </ol>
        </fieldset>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/admin/articles/approve_with_comments.html.erb
<div class="fancybox_outlayer">
<div class="title_bar" id="title_bar">
  <div id="titlebar_left">
    <h2 id="page_title">Approve Article With Comments</h2>
  </div> 
</div>
<div class="flashes"></div>
<div id="active_admin_content" class="without_sidebar">
  <div id="main_content_wrapper">
    <div id="main_content">

      <%= form_for(@article, url: approve_with_comments_update_admin_article_path, method: :post, remote: true, html: {class: "formtastic"}) do |f| %>
        <fieldset class="inputs"><!-- inputs -->
          <ol>
            <li class="" id="article_line_manager_id_input">
              <%= f.label :line_manager %>
              <%= f.select(:line_manager_id, LineManager.all.collect {|s| [s.name, s.id ] }, { include_blank: true }, class: "form-control") %>
            </li>
            <li class="" id="article_editor_id_input">
              <%= f.label :editor %>
              <%= f.select(:editor_id, Editor.all.collect {|s| [s.name, s.id ] }, { include_blank: true }, class: "form-control") %>
            </li>
            <li class="" id="article_approval_comments_input">
              <%= f.label :approval_comments %>
              <%= f.text_area :approval_comments, class: "form-control", rows: "3" %>
            </li>
          </ol>
        </fieldset>

        <fieldset class="actions">
          <ol>
            <li class="cancel">
              <%= link_to "Cancel", modal_cancel_admin_article_path(@article), remote: true %>
            </li>
            <li id="article_submit_action" class="action input_action ">
              <input type="submit" value="Approve" name="commit">
            </li>
            <!-- <li class="cancel">
              <a href="/admin/mailboxer_conversations">إلغاء</a>
            </li> -->
          </ol>
        </fieldset>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/admin/articles/quick_response.js.erb
<% if @article.errors.any? %>
  var html = "<%= escape_javascript(render 'error_messages', object: @article) %>";
  $('#quick-add-errors').html(html);
<% else %>
  window.location.reload();
<% end %>